version: '3.4'

services:
  keycloak:
    #image: wizzn/keycloak:12
    image: jboss/keycloak:13.0.0
    container_name: ${CONTAINER_NAME}
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/realm-test.json
    volumes:
      - ./realm-test.json:/tmp/realm-test.json
