version: '3.4'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: ${CONTAINER_NAME}
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-test.json
    volumes:
      - ./realm-test.json:/tmp/realm-test.json
