version: '3.4'

services:
  keycloak:
    image: jboss/keycloak:13.0.0
    container_name: keycloack-mlops
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-dev.json
    volumes:
      - ./realm-dev.json:/tmp/realm-dev.json
    networks:
      - mlops-network

  psql-db:
    image: postgres:12.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
    networks:
      - mlops-network
networks:
  mlops-network:
    driver: bridge
