name: secret-scanning

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: trufflehog-actions-scan
        uses: nathankleyn/trufflehog-actions-scan@master
        with:
          scanArguments: '--regex --entropy=False --max_depth=5 --rules .secretsmatchers.json --exclude_paths .secretsignore'
        if: failure()
